// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk-B-B8BeZSjl6lDsV_yHscBsZzXBkPMg',
    appId: '1:662652280138:web:7c54cc8e251a5ab23d75b3',
    messagingSenderId: '662652280138',
    projectId: 'harmonize-32e98',
    authDomain: 'harmonize-32e98.firebaseapp.com',
    storageBucket: 'harmonize-32e98.appspot.com',
    measurementId: 'G-GYX9ZX8T3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRuWYlWFnH0y-AeT2Oa1IMYpJHNfggO_o',
    appId: '1:662652280138:android:77b9136e85f0af7b3d75b3',
    messagingSenderId: '662652280138',
    projectId: 'harmonize-32e98',
    storageBucket: 'harmonize-32e98.appspot.com',
  );
}
